spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/TheMaheshBiradar/config-repo.git
          #search-paths:
          #  -
          #  -
server:
  port: 8887

